[features]
seeds = false
skip-lint = false
[programs.devnet]
chainlink_dapp = "HoUw6cAzx7LqcuF9r7pUhj9uyZ7ppEnzuKAJDd3EsZR8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/willowsenator/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
